// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAbNlzDTKqudptvK9drXsnES4oL6EFkSc',
    appId: '1:630224729480:web:a1a3bd31d6f221ad1ab63d',
    messagingSenderId: '630224729480',
    projectId: 'muhammad-yaseen-522d7',
    authDomain: 'muhammad-yaseen-522d7.firebaseapp.com',
    storageBucket: 'muhammad-yaseen-522d7.firebasestorage.app',
    measurementId: 'G-EXB06PRTMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuHGlsv7GiIatwerXtvYUYrpehil-cFtg',
    appId: '1:630224729480:android:f3d47dcf1a13f54f1ab63d',
    messagingSenderId: '630224729480',
    projectId: 'muhammad-yaseen-522d7',
    storageBucket: 'muhammad-yaseen-522d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVosPew9Pa5o-50OUOhjC4D8LClDR7UVE',
    appId: '1:630224729480:ios:a27f4f155fba86741ab63d',
    messagingSenderId: '630224729480',
    projectId: 'muhammad-yaseen-522d7',
    storageBucket: 'muhammad-yaseen-522d7.firebasestorage.app',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVosPew9Pa5o-50OUOhjC4D8LClDR7UVE',
    appId: '1:630224729480:ios:a27f4f155fba86741ab63d',
    messagingSenderId: '630224729480',
    projectId: 'muhammad-yaseen-522d7',
    storageBucket: 'muhammad-yaseen-522d7.firebasestorage.app',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAbNlzDTKqudptvK9drXsnES4oL6EFkSc',
    appId: '1:630224729480:web:be50fab243b517e51ab63d',
    messagingSenderId: '630224729480',
    projectId: 'muhammad-yaseen-522d7',
    authDomain: 'muhammad-yaseen-522d7.firebaseapp.com',
    storageBucket: 'muhammad-yaseen-522d7.firebasestorage.app',
    measurementId: 'G-722KCR2DBX',
  );
}
